### ISSUE TITLE
[P5R] Black Screen on Launch if Persona Essentials activated in Reloaded-II

### ISSUE THREAD

**Issue by InsideCat02** [Sewer56/p5rpc.modloader#33]
I'm not sure what's going on, I didn't have this problem before, not sure if I did anything different since the last time I tried to play and mod P5R, but some reason my game refuses to load up beyond the window popping up if Essentials is turned on in Reloaded-II. This issue seems to persist with or without the ASI Loader method of launching the game, or via Reloaded-II without the ASI Loader, or via shortcut. I figure, maybe it's a 2.7.0 issue, but even re-downloading the latest GameBanana version (which goes all the way back to 1.2.0?) seems to still cause this problem.

I'm hoping that despite my looking anywhere and everywhere to find a solution or more info into the possible issue and failing to find anything isn't just a full user error here, because I definitely did my best before submitting this issue here. 😅

**Comment by Sewer56** [comment]
Consider posting a log :p

**Comment by InsideCat02** [comment]
Sorry, where do I find that, cause I'm actually on the hunt for it right now!

**Comment by Sewer56** [comment]
There's a button in the main window of the launcher which says `View Log Files`. It will take you to the folder where the latest logs are stored.

**Comment by InsideCat02** [comment]
Just added one to my last comment, I found it immediately after posting it, and I know good and well I can't really follow what the issue might be, but for some reason with it on, it seems to get stuck at "[22:30:00] Found Window, Hooking WndProc." every time the problem occurs.

**Comment by Sewer56** [comment]
Not really sure why it's stalling.
Maybe try toggling the other mod (Fix Shadow Settings) orayvd try toggling Skipping Intro in Essentials' menu.

**Comment by InsideCat02** [comment]
Here's the result of toggling Fix Shadow Settings (same stall on the window popping up)
[2024-05-30 02.51.37 ~ P5R.txt](https://github.com/Sewer56/p5rpc.modloader/files/15493115/2024-05-30.02.51.37.P5R.txt)

And here's the result of toggling Skip Intro on (with Fix Shadow Settings off)
[2024-05-30 02.54.03 ~ P5R.txt](https://github.com/Sewer56/p5rpc.modloader/files/15493136/2024-05-30.02.54.03.P5R.txt)

Also, I've actually just freshly installed P5R since a few days ago and taking time to add all the mods I wanted before starting a fresh game (which on that same note, I actually cleared all save data to start entirely from scratch.)

The only consistent fix is disabling Persona Essentials some reason (whether that's GB's P5R 1.2.0 version or the latest 2.7.0 version hosted here.)
[2024-05-30 02.55.59 ~ P5R.txt](https://github.com/Sewer56/p5rpc.modloader/files/15493161/2024-05-30.02.55.59.P5R.txt)

**Comment by InsideCat02** [comment]
Okay, oh my god, I had a vague suspicion but only just finally confirmed it. In case someone else needs help with this sort of issue, and you ALSO have a laptop with both an iGPU and dedicated GPU inside it, make ABSOLUTE SURE your game is running on the dedicated GPU and not the integrated GPU. 

I corrected this in the past, but I guess since I'm running the game from a different location as I was then (Gone from C: Drive to an external SSD drive), and Nvidia still doesn't automatically give P5R a profile to use dedicated GPUs (???), it wasn't running on the dedicated GPU I guess, and some reason the game/mods DESPISED the integrated GPU so much that the game just froze immediately upon the window popping up.
